### PR TITLE
Check if method getLockFile exists

### PR DESCRIPTION
**Pull request by peter-mw**
on Composer version 1.8.0 method getLockFile does not exist and leads to error

`PHP Fatal error:  Uncaught Error: Call to undefined method Composer\Factory::getLockFile() in G:\xampp\htdocs\project\vendor\wikimedia\composer-merge-plugin\src\MergePlugin.php:323`

---
This change is [Reviewable](https://reviewable.io/reviews/mcaskill/composer-merge-plugin/1)

### CODE REVIEW

**Comment by LukeTowers** [comment]
Why wouldn't you just update to the latest 1.x release?

**Comment by peter-mw** [comment]
because i need to keep BC 

most users still have not updated composer

**Comment by LukeTowers** [comment]
What breaks between 1.8 and 1.10?

**Comment by peter-mw** [comment]
seems to be running fine just the method `getLockFile` does not exists in 1.8

i have tested on both versions and its ok

**Comment by LukeTowers** [comment]
My point is more so that this change has the potential to falsely support a composer version that isn't actually supported fully, causing it to break in unknown ways. With that in mind, I'm curious to know more about the situation where someone is unable / unwilling to upgrade composer from 1.8 to 1.10 so it can work properly with this. I understand wanting to avoid the upgrade to 2.0 from 1.x, but I don't see why anyone would avoid upgrading from 1.8 to 1.10.

**Comment by peter-mw** [comment]
Hello, if you read the code you will see that this check is used to display a message if you fail to update.

It does not break anything. People with older composer just wont see a message on fail

**Comment by peter-mw** [comment]
seems fixes are already been made, thanks @mcaskill

**Comment by mcaskill** [comment]
Sorry about that. I wasn't aware there was a pull request on my fork.
I've made sure notifications are on from now on.

**Pull request closed without merging**
